### ISSUE TITLE
Snippets not working

### ISSUE THREAD

**Issue by clauderoy790** [honnamkuan/vscode-golang-snippets#3]
I just installed the extension and the snippets are not working for me. I tried restarting VS code but they still aren't showing up and aren't working even if I try to press tab or ctrl and/or cmd.
I tried disabling my Vim extension but that wasn't the problem.

OS: Mac OS Monterey
Vs Code Version: 1.67.2
Go Version: 1.17.5
Golang Snippets Version: v1.1.0
Go Extension Version: v0.33.1

Any ideas?

**Comment by kuator** [comment]
> I just installed the extension and the snippets are not working for me. I tried restarting VS code but they still aren't showing up and aren't working even if I try to press tab or ctrl and/or cmd. I tried disabling my Vim extension but that wasn't the problem.
> 
> OS: Mac OS Monterey Vs Code Version: 1.67.2 Go Version: 1.17.5 Golang Snippets Version: v1.1.0 Go Extension Version: v0.33.1
> 
> Any ideas?

https://github.com/kuator/vscode-golang-snippets

**Comment by kuator** [comment]
> I just installed the extension and the snippets are not working for me. I tried restarting VS code but they still aren't showing up and aren't working even if I try to press tab or ctrl and/or cmd. I tried disabling my Vim extension but that wasn't the problem.
> 
> OS: Mac OS Monterey Vs Code Version: 1.67.2 Go Version: 1.17.5 Golang Snippets Version: v1.1.0 Go Extension Version: v0.33.1
> 
> Any ideas?

Extra comma breaks the json file

**Comment by clauderoy790** [comment]
I found out what the problem was. It even works as is now even with the extra comma in the JSON. I had the following setting in my vscode settings that was blocking all snippets from showing

`  "[go]": {
    // "editor.snippetSuggestions": "none", <-- remove/comment this
  },`

It took me a while to notice it.

Thanks for the help :)
